### ISSUE TITLE
Can't convert logical partitions to bcache

### ISSUE THREAD

**Issue by Khrundel** [g2p/blocks#5]
Encountered issue similar to
https://github.com/g2p/blocks/issues/1
but can't fix it mentioned way.
I've installed ubuntu 13.10 x64.
primary /dev/sdc1 (512MB) mounted to /boot
/dev/sdc2 is extended partition containing:
  /dev/sdc5  (swap)
  /dev/sdc6  (/)
  /dev/sdc7 (bcache0 mounted to /home)
I'm trying to convert root filesystem to bcache using blocks.
blocks told me "The range we want to reserve overlaps with the start of partition /dev/sdc-1 (metadata), the shrinking strategy will not work."
Moved /dev/sdc1 1 mb from beginning - got same message. Moved 15 MB - same effect. Created new "cleared" partition at the beginning of disk and than removed it (I believe, this should overwrite any data at that place - got same message.
Any ideas how to fix this?

**Comment by g2p** [comment]
I'm realising that logical partitions like /dev/sdc6 have [a small bit of reserved data](https://en.wikipedia.org/wiki/Extended_boot_record) immediately before them. The "-1" in "sdc-1" is bogus (I've just fixed the error message) and must be referring to that area. I think it's okay to not error out in that case because parted will move the EBR, but libparted doesn't make it easy to detect that it's an EBR.

**Comment by g2p** [comment]
Converting logical partitions to bcache would be complex and possibly fragile, so I've updated the README to recommend converting to GPT first.
